/* Generated by Cython 3.2.4 */

#ifndef __PYX_HAVE__kivy_thor_provider___ktp
#define __PYX_HAVE__kivy_thor_provider___ktp

#include "Python.h"

#ifndef __PYX_HAVE_API__kivy_thor_provider___ktp

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void ktp_widget_canvas_draw(void *, void *);
__PYX_EXTERN_C void ktp_widget_destroy(void *);
__PYX_EXTERN_C void *ktp_canvas_wrap(void *);
__PYX_EXTERN_C void ktp_canvas_release(void *);

#endif /* !__PYX_HAVE_API__kivy_thor_provider___ktp */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("_ktp", PyInit__ktp) instead of calling PyInit__ktp directly from Python 3.5 */
PyMODINIT_FUNC PyInit__ktp(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"_ktp\", PyInit__ktp) instead of calling PyInit__ktp directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"_ktp\", PyInit__ktp) instead of calling PyInit__ktp directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"_ktp\", PyInit__ktp) instead of calling PyInit__ktp directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit__ktp_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit__ktp() __PYX_WARN_IF_PyInit__ktp_INIT_CALLED(PyInit__ktp())
#endif

#endif /* !__PYX_HAVE__kivy_thor_provider___ktp */
