# _ktp.pyi — type stubs for _ktp.pyx
from typing import Any, Callable, Deque, Optional, Tuple, Union


# ---------------------------------------------------------------------------
# Module-level functions
# ---------------------------------------------------------------------------

def app_init(embedded: bool = False) -> None:
    """Bootstrap the platform application runtime.

    embedded=False  standalone: Python owns the process, Swift bootstraps NSApplication.
    embedded=True   embedded:   host NSApplication already running (Xcode / native app).
    """
    ...

def engine_start(threads: int = 4) -> None:
    """Start the ThorVG engine.  Safe to call more than once.
    threads=0 lets Swift choose a default.
    """
    ...

def engine_stop() -> None:
    """Stop the ThorVG engine and release its resources."""
    ...

def window_create(
    x: Optional[int] = None,
    y: Optional[int] = None,
    width: int = 800,
    height: int = 600,
    borderless: bool = False,
    fullscreen: bool = False,
    resizable: bool = True,
    state: Optional[str] = None,
) -> _KtpWindowStorage:
    """Create a native window and return a ready-to-use _KtpWindowStorage.

    Typical standalone usage::

        import kivy_thor_provider as ktp

        ktp.app_init()                          # bootstrap NSApplication once
        win = ktp.window_create(width=1280, height=720)
        win.set_frame_handler(lambda dt: ...)   # called every vsync

        while True:
            event = win.poll()
            if not event:
                break
            ...
    """
    ...

# Event tuple types
EventTuple = Union[
    Tuple[str, float, float],  # mousemotion
    Tuple[str, float, float, int],  # mousebuttondown, mousebuttonup
    Tuple[str, float, float, float, float],  # fingerdown, fingermotion, fingerup
    Tuple[str, int, int, int, Optional[str]],  # keydown, keyup
    Tuple[str, str],  # textinput, textedit, dropfile, droptext
    Tuple[str, int, int],  # windowresized, windowmoved
    Tuple[str],  # windowclose, windowfocusgained, windowfocuslost, windowminimized, windowmaximized, windowrestored, windowshown, windowhidden, windowexposed, windowenter, windowleave, dropbegin, dropend, quit
    Tuple[str, float, float, Optional[Any]],  # mousewheel events
]

class _KtpWindowStorage:
    _win: Any
    _event_queue: Deque[EventTuple]
    _event_filter: Optional[Callable[..., Any]]
    _frame_handler: Optional[Callable[[float], Any]]
    _titlebar_handler: Optional[Callable[[int, int], int]]

    def __cinit__(self) -> None: ...
    def __dealloc__(self) -> None: ...
    def set_event_filter(self, event_filter: Optional[Callable[..., Any]]) -> None: ...
    def set_frame_handler(self, handler: Optional[Callable[[float], Any]]) -> None: ...
    def setup_window(self, x: Optional[int], y: Optional[int], width: int, height: int,
                     borderless: bool, fullscreen: bool, resizable: bool, state: Union[str, int]) -> Tuple[int, int]: ...
    def teardown_window(self) -> None: ...
    def resize_window(self, w: int, h: int) -> None: ...
    def poll(self) -> Union[EventTuple, bool]: ...
    def set_window_title(self, title: str) -> None: ...
    def set_window_icon(self, filename: str) -> None: ...
    def set_window_pos(self, x: Optional[int], y: Optional[int]) -> None: ...
    def get_window_pos(self) -> Tuple[int, int]: ...
    @property
    def window_size(self) -> list[int]: ...  # returns [w, h]
    @property
    def window_pixel_size(self) -> Tuple[int, int]: ...
    def set_window_opacity(self, opacity: float) -> bool: ...
    def get_window_opacity(self) -> float: ...
    def get_window_pixel_density(self) -> float: ...
    def get_window_display_scale(self) -> float: ...
    def set_minimum_size(self, w: int, h: int) -> None: ...
    def set_always_on_top(self, on: bool) -> None: ...
    def set_allow_screensaver(self, allow: bool) -> None: ...
    def set_border_state(self, borderless: bool) -> None: ...
    def set_fullscreen_mode(self, mode: Union[bool, str]) -> None: ...
    def maximize_window(self) -> None: ...
    def minimize_window(self) -> None: ...
    def restore_window(self) -> None: ...
    def hide_window(self) -> None: ...
    def show_window(self) -> None: ...
    def raise_window(self) -> None: ...
    def _set_cursor_state(self, visible: bool) -> None: ...
    def set_system_cursor(self, name: str) -> bool: ...
    def grab_mouse(self, grab: bool) -> None: ...
    def get_relative_mouse_pos(self) -> Tuple[float, float]: ...
    def show_keyboard(self, system_keyboard: Any, softinput_mode: Any, input_type: str, keyboard_suggestions: bool = True) -> None: ...
    def hide_keyboard(self) -> None: ...
    def is_keyboard_shown(self) -> bool: ...
    def get_current_key_modifiers(self) -> int: ...
    def is_window_shapable(self) -> bool: ...
    def set_shape(self, shape_image: Any) -> None: ...
    def save_bytes_in_png(self, filename: str, data: bytes, width: int, height: int) -> None: ...
    def set_custom_titlebar(self, titlebar_widget: Any) -> int: ...
    def get_system_theme(self) -> str: ...
    def get_canvas(self) -> int: ...
    def get_canvas_size(self) -> Tuple[int, int]: ...
